const prompts = {
  morning: [
    "What am I most grateful for today?",
    "What is my biggest goal for today?",
    "How can I make today meaningful?",
    "What is one positive affirmation I will repeat to myself today?",
    "Who needs my support or encouragement today?",
    "What is one healthy choice I can make today?",
    "What does success look like for me today?",
    "How will I ensure my mental and emotional well-being today?",
    "What will I do to stay focused on my priorities?",
    "How can I practice mindfulness in my morning routine?",
    "What is one thing I can let go of today?",
    "What challenges might I face today, and how will I prepare?",
    "What am I excited about today?",
    "What is one skill I can improve today?",
    "What’s a new habit I can try to implement today?",
    "What can I do to inspire someone else today?",
    "What’s one thing I’ll avoid today to stay productive?",
    "What is one thing I will finish today?",
    "What’s a quote or mantra I’ll keep in mind today?",
    "What’s one small way I’ll step out of my comfort zone today?",
    "What’s something I’m looking forward to?",
    "What are my top three priorities today?",
    "What’s one thing I can declutter from my life today?",
    "What is one area of self-improvement I can focus on today?",
    "How can I simplify my day ahead?",
    "How will I show gratitude today?",
    "What’s one personal boundary I’ll set today?",
    "What is the best use of my time this morning?",
    "What’s a fun activity I can incorporate into my day?",
    "How will I take care of my body today?",
    "What’s something I’ll do to nurture my creativity?",
    "What’s one new perspective I can explore today?",
    "What can I do to spread kindness today?",
    "What’s one thing I can accomplish in the next hour?",
    "How can I create joy for myself today?",
    "What is one thing I’ll prioritize over everything else?",
    "What’s one way I’ll make progress on my long-term goals?",
    "What’s something I’ll celebrate today, no matter how small?",
    "What’s a small way I’ll reward myself today?",
    "What’s one habit I want to stick to today?",
    "What’s a lesson from yesterday I can apply today?",
    "What’s one thing I’m passionate about that I can nurture today?",
    "How will I protect my energy today?",
    "What’s one new experience I can embrace today?",
    "What’s a memory I cherish that motivates me this morning?",
    "What’s one area of my life I want to improve today?",
    "What is something I’ll enjoy doing this morning?"
    // Add more as needed, aiming for at least 100 prompts total
  ],
  afternoon: [
    "What’s one thing I’ve accomplished today so far?",
    "What’s the biggest lesson I’ve learned today?",
    "What’s one thing I can focus on this afternoon?",
    "How can I re-energize myself for the rest of the day?",
    "What’s one way I can stay productive this afternoon?",
    "How can I express gratitude for the progress I’ve made?",
    "What’s one way I can reduce stress right now?",
    "What’s something I’ll prioritize for the next hour?",
    "What’s one thing I’ll finish before the end of the day?",
    "What’s something I can celebrate about my progress so far?",
    "How can I prepare for the rest of my day?",
    "What’s something I can do to feel proud of myself by evening?",
    "How will I avoid distractions for the rest of the day?",
    "What’s a kind action I can take this afternoon?",
    "What’s one thing I’ll focus on improving today?",
    "What’s a healthy choice I can make this afternoon?",
    "What’s one thing I can do to simplify my workload?",
    "What’s one skill I can practice or refine this afternoon?",
    "What’s something I can delegate or remove from my to-do list?",
    "How can I connect with someone this afternoon?",
    "What’s one thing I’ll do to feel fulfilled by evening?",
    "What’s a small win I can aim for by the end of the day?",
    "What’s a way I can show appreciation for myself or others?",
    "What’s something I can look forward to later today?",
    "How can I practice mindfulness this afternoon?",
    "What’s something new I’ve learned so far today?",
    "What’s a positive mindset I can carry into the evening?",
    "What’s something I can reflect on to improve my focus?",
    "What’s one thing I can plan for tomorrow?",
    "What’s something I’ve overcome so far today?",
    "How can I make the most of my remaining time today?",
    "What’s a creative idea I can work on this afternoon?",
    "What’s a goal I can review this afternoon?",
    "What’s something I’ll do differently this afternoon?",
    "What’s one way I can practice gratitude before the evening?"
    // Add more as needed, aiming for at least 100 prompts total
  ],
  night: [
    "What am I most proud of today?",
    "What’s something I’m grateful for today?",
    "What was the highlight of my day?",
    "What’s one thing I learned about myself today?",
    "What’s one way I made progress on my goals today?",
    "What’s something I’ll carry forward to tomorrow?",
    "What’s a lesson I learned today?",
    "What’s one thing I could have done better today?",
    "What’s something I’ll let go of tonight?",
    "What’s one thing I accomplished that felt meaningful?",
    "What’s one thing I’m excited about tomorrow?",
    "What emotions did I feel today, and why?",
    "What’s one kind thing someone did for me today?",
    "What’s one kind thing I did for someone else?",
    "What’s one habit I stuck to today?",
    "What’s something I overcame today?",
    "What’s one thing I enjoyed doing today?",
    "What’s something I want to reflect on tonight?",
    "What’s a memory from today I want to keep?",
    "What’s one way I balanced work and rest today?",
    "What’s one thing I’ll do differently tomorrow?",
    "What’s one thing I’m letting go of before bed?",
    "How did I nurture myself today?",
    "What’s something I’ll dream about tonight?",
    "What’s one creative idea I had today?",
    "What’s a positive memory from today I want to hold onto?",
    "What’s one thing I’ll do tomorrow to improve my day?",
    "What’s a small joy I experienced today?",
    "What’s one thing I’m grateful to my body for today?",
    "What’s something I accomplished that felt fulfilling?",
    "What’s one way I showed resilience today?",
    "What’s something I learned from today’s challenges?",
    "What’s something that made me laugh today?",
    "What’s one thing I’m looking forward to tomorrow?",
    "What’s something I’ll plan better next time?"
    // Add more as needed, aiming for at least 100 prompts total
  ]
};

export default prompts;
